### ISSUE TITLE
UnboundLocalError: local variable 'model' referenced before assignment

### ISSUE THREAD

**Issue by NantiaL** [manuelgloeckler/ncmw#8]
Hey! I just installed the current version of NCMW and as I tried to run the first step, which is the `ncmw_setup` I got the following error: 

```
[2022-05-12 11:03:10,587][ncmw.scripts.setup_scripts][INFO] - Hostname: retinol
[2022-05-12 11:03:10,587][ncmw.scripts.setup_scripts][INFO] - Random seed: 1
[2022-05-12 11:03:10,587][ncmw.scripts.setup_scripts][INFO] - Generating result directory in /Users/leonidou/ncmw/results/default_project_name/setup
[2022-05-12 11:03:10,588][ncmw.scripts.setup_scripts][INFO] - Loading all models in the folder /Users/leonidou/ncmw/data/models
Error executing job with overrides: []
Traceback (most recent call last):
  File "/Users/leonidou/ncmw/ncmw/scripts/setup_scripts.py", line 35, in run_setup_hydra
    run_setup(cfg)
  File "/Users/leonidou/ncmw/ncmw/scripts/setup_scripts.py", line 138, in run_setup
    models = get_models(models_folder)
  File "/Users/leonidou/ncmw/ncmw/utils/utils_io.py", line 147, in get_models
    models.append(model)
UnboundLocalError: local variable 'model' referenced before assignment

```

Any idea why the error occurs? With the previous version, I was able to successfully run the tool. 
Thanks in advance!

**Comment by manuelgloeckler** [comment]
Hey!

I have a pretty good idea of how this is caused. Does your model start with a "." or is there any file in the model folder which starts with ".". If you use MacOS then such files will be created automatically after some operations i.e. creating this folder after deletion (I don't have any Apple devices so I cannot test it). Further, these files are typically invisible to the user... (if you don't make them visible in the terminal). Hence, the error did only appear after some time (I think once you modified the model's folder).

I included a line of code, which should prevent this error from happening i.e. all files which start with a point are skipped. Please reinstall the package and try it again. Let me know if this fixes the error. Otherwise please provide a full overview of which files are with the data/models folder i.e. by using ls -a within your terminal.

Kind regards
Manuel

**Comment by draeger** [comment]
In unixoid operating systems, a file or folder (note that Unix treats files and folders identically) name starting with a period (dot) indicates that that file is hidden. So, normal folders shouldn't start with a dot. What macOS automatically generates in many folders is `.DS_Store`. Does this file cause those problems?

**Comment by NantiaL** [comment]
None of my model files' names start with a dot. However, there are three hidden files in my data/models directory, which must have been generated automatically by macOS.

Thank you for your help! I will download the new version and try again!

**Comment by NantiaL** [comment]
It works fine now! Thanks a lot! I will then close this issue.
